sudo: required

services:
  - docker

language: scala

scala:
- 2.12.3

before_script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
- sbt ++$TRAVIS_SCALA_VERSION test
- sbt ++$TRAVIS_SCALA_VERSION docker:publish
